### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jbee37142** [JaeYeopHan/Navigation_Component#2]
## TODO
* [ ] Add Unit Test 
* [ ] Add Karma
* [ ] Apply coverall and istanbul to test coverage with badge
* [ ] Add `:hover` to CSS
    * just for design and UX
* [ ] Apply tree shaking (webpack)
* [ ] Fix `package.json` github url (issue and readme)
